import { Inter } from "next/font/google";
import "../styles/_reset.scss";
import "../styles/globals.scss";
import styles from "./layout.module.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <title>SushiCTFx</title>
        </header>
        <div className={styles.root}>
          <div className={styles.root_container}>{children}</div>
        </div>
        <footer>
          <small>© 2023 yu1hpa</small>
        </footer>
      </body>
    </html>
  );
}
